# Generated by Django 5.1.13 on 2026-01-27 19:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uri", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("data_type", models.CharField(blank=True, max_length=50, null=True)),
                ("image", models.URLField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="fetchlog",
            name="message",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("uri", models.CharField(max_length=255, unique=True)),
                ("url", models.URLField(blank=True, max_length=1000, null=True)),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("body", models.TextField(blank=True, null=True)),
                ("lang", models.CharField(blank=True, max_length=10, null=True)),
                ("data_type", models.CharField(blank=True, max_length=20, null=True)),
                ("sentiment", models.FloatField(blank=True, null=True)),
                ("relevance", models.IntegerField(blank=True, default=0, null=True)),
                ("image", models.URLField(blank=True, max_length=1000, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("authors", models.JSONField(blank=True, default=list, null=True)),
                ("concepts", models.JSONField(blank=True, default=list, null=True)),
                ("categories", models.JSONField(blank=True, default=list, null=True)),
                ("raw_data", models.JSONField(blank=True, null=True)),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="news.source",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
    ]
