# Generated by Django 6.0.1 on 2026-01-28 12:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("news", "0002_source_alter_fetchlog_message_article"),
    ]

    operations = [
        migrations.CreateModel(
            name="Citation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary_sentence", models.TextField()),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CitationSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentence", models.TextField()),
                ("expert_name", models.TextField(blank=True, null=True)),
                ("article_uuid", models.TextField()),
                ("article_source", models.TextField(blank=True, null=True)),
                ("article_title", models.TextField(blank=True, null=True)),
                ("article_url", models.TextField(blank=True, null=True)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citation_sources",
                        to="news.article",
                    ),
                ),
                (
                    "citation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="multi_agent_systems.citation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("summary_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article_count",
                    models.IntegerField(default=0, help_text="Number of articles used"),
                ),
                ("date_range_start", models.DateTimeField(blank=True, null=True)),
                ("date_range_end", models.DateTimeField(blank=True, null=True)),
                ("agent_name", models.TextField(default="dn_mas")),
                (
                    "articles_provided",
                    models.ManyToManyField(
                        blank=True,
                        help_text="All articles provided to the agent for processing",
                        related_name="summaries_as_input",
                        to="news.article",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Summaries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="citation",
            name="summary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="citations",
                to="multi_agent_systems.summary",
            ),
        ),
    ]
