# Generated by Django 6.0.1 on 2026-01-28 15:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("multi_agent_systems", "0001_initial"),
        ("news", "0002_source_alter_fetchlog_message_article"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicAnalysisGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("agent_name", models.TextField(default="st_mas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "articles_provided",
                    models.ManyToManyField(
                        related_name="topic_analysis_groups", to="news.article"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Topic Analysis Groups",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TopicAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic_name", models.TextField()),
                ("sentiment", models.CharField(max_length=20)),
                ("summary_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="multi_agent_systems.topicanalysisgroup",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Topic Analyses",
            },
        ),
        migrations.CreateModel(
            name="TopicCitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary_sentence", models.TextField()),
                ("order", models.IntegerField(default=0)),
                (
                    "topic_analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary_citations",
                        to="multi_agent_systems.topicanalysis",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TopicCitationSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentence", models.TextField()),
                ("expert_name", models.TextField(blank=True, null=True)),
                ("article_uuid", models.TextField()),
                ("article_source", models.TextField(blank=True, null=True)),
                ("article_title", models.TextField(blank=True, null=True)),
                ("article_url", models.TextField(blank=True, null=True)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_citation_sources",
                        to="news.article",
                    ),
                ),
                (
                    "topic_citation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="multi_agent_systems.topiccitation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TopicExpert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expert_name", models.TextField()),
                ("organization", models.TextField()),
                ("opinion", models.TextField()),
                ("sentiment", models.CharField(max_length=20)),
                (
                    "topic_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experts",
                        to="multi_agent_systems.topicanalysis",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="topiccitation",
            name="expert",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="citations",
                to="multi_agent_systems.topicexpert",
            ),
        ),
        migrations.CreateModel(
            name="TopicMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("value", models.TextField()),
                ("period", models.TextField()),
                ("discussion", models.TextField()),
                ("sentiment", models.CharField(max_length=20)),
                (
                    "topic_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="multi_agent_systems.topicanalysis",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="topiccitation",
            name="metric",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="citations",
                to="multi_agent_systems.topicmetric",
            ),
        ),
    ]
