# Generated by Django 5.1.13 on 2026-01-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("multi_agent_systems", "0003_topicanalysisgroup_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="summary",
            name="context",
            field=models.CharField(
                default="general",
                help_text="Analysis context: pre_announcement, post_announcement, general",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="summary",
            name="fomc_announcement_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="topicanalysisgroup",
            name="fomc_announcement_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
