# Generated by Django 5.1.13 on 2026-01-30 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "multi_agent_systems",
            "0004_summary_context_summary_fomc_announcement_datetime_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="summary",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="topicanalysis",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="topicanalysisgroup",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
