# Generated by Django 5.1.13 on 2026-01-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("multi_agent_systems", "0005_alter_summary_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True)),
                ("value", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
